### ISSUE TITLE
Find out if we can download videos in highest quality available

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.go#11]
Niko  mentioned we are using a setting for the yt downloader that's supposed to get the best qualify video available. A user recently reached out asking what format his videos will be uploaded it and when I did some digging, it looks like we are only grabbing 720p versions.

Example:
https://www.youtube.com/watch?v=NIVms5W0PqQ - has 1080p60 option, but the file we have is in 720p lbry://attack-on-titan-2-review-fight-on#bb202489329ca6f7639e38101c5fc83e265088e7

**Comment by alyssaoc** [comment]
@nikooo777 and @tzarebczan Is this issue still relevant?

**Comment by nikooo777** [comment]
@tzarebczan i think that with the latest changes it always picks the best quality available. have you see instances where this is not true?

**Comment by tzarebczan** [comment]
I think it's only grabbing up to 720P, which is probably the largest we want due to storage constraints. Would be good to know why it isn't trying to grab the 1080p copy.
