### ISSUE TITLE
Rename this repo

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.go#17]
`lbry.go` is a confusing name for what this does.

Also, should this be public?

**Comment by tiger5226** [comment]
please let me know if we do this as Chainquery depends on its packages.

**Comment by tiger5226** [comment]
We use a lot of stuff. So does internal-apis. It is the repo grin has designated as the Go repo for all things LBRY. So if anything is shared between go apps it goes here. Specifically from the gopkg.lock file 

```
packages = [
    "api",
    "errors",
    "jsonrpc",
    "lbrycrd",
    "null",
    "querytools",
    "stop",
    "travis",
    "util",
    "validator"
  ]
```

**Comment by kauffj** [comment]
So obviously this repo should be named `lbry-libraries.go`.

**Comment by tiger5226** [comment]
how about bookshelf.go? Stays with the LBRY theme and signifies lots of choices. No strong preference, just thought it was a playful name. @lyoshenka remarked "The swiss army knife" previously, although I think he removed that for the same reasons you want to rename the repo. 

I strongly believe any lbry.go repo should be reserved for the daemon rewrite as that is what any one would think this repo was. 

Additionally, lbryschema.go, and reflector.go use this as well I believe.

**Comment by alyssaoc** [comment]
@kauffj and @lyoshenka is this something you want to tackle? It won't be easy, but sooner rather than later. Perhaps a better readme?

**Comment by kauffj** [comment]
This is for @lyoshenka only. I noticed he already started splitting some parts of this repo out.

**Comment by lyoshenka** [comment]
ill rename this eventually

**Comment by alyssaoc** [comment]
closing for now
