### ISSUE TITLE
add support for priced content

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry.go#18]
Some content publishers want to have their videos published for a price.
For this reason ytsync must fetch the following parameters from the API: `fee_amount`, `fee_currency`, `fee_address` and then supply them when calling the publish method.
This issue depends on the implementation on the API side first.

**Comment by tzarebczan** [comment]
We recently synced some content without a price for a creator who was promised we'd sync at 1 LBC.

**Comment by nikooo777** [comment]
and I agree that's a problem. I will try to get this in my next sprint

**Comment by alyssaoc** [comment]
Issue moved to [lbryio/ytsync #6](https://github.com/lbryio/ytsync/issues/6) via [**ZenHub**](https://www.zenhub.com/)
