### ISSUE TITLE
Cannot publish empty file /tmp/ytsync006303211/RjelTxxXQxA/hypixel-tnt-run-come-and-play.mp4

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.go#27]
Is this an issue on our side or something went wrong during the rip/transfer process?

**Comment by nikooo777** [comment]
I believe this is related to disk space running out. I'll add space checks before starting a download.
The above happened because i blatantly ignored the 90% disk check while trying to finish a channel. 

Chernobyl 2.0

**Comment by nikooo777** [comment]
introduced an additional check and it's now most likely solved for good.

**Comment by nikooo777** [comment]
unfortunately I saw this happen again. while it's not a big deal because the video will be retried, it's still weird and not easy to track. Could be related to connection errors. I'll update the ytdl library
