### ISSUE TITLE
video is bigger than 2GB, skipping for now

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.go#28]
We should determine if we'll ever be syncing larger videos than 2 GB and if so, when would be a good time to process them (probably after adding publish date metadata).

**Comment by nikooo777** [comment]
we can leave this issue pending. Whenever we decide we want to sync them as well we just have to process them instead of skipping them. Very easy to do

**Comment by kauffj** [comment]
@nikooo777 do you save the file size in the video table? Possibly worth adding this if you do not

**Comment by nikooo777** [comment]
I don't, i'll add that

**Comment by alyssaoc** [comment]
closing for now, will revisit later
