### ISSUE TITLE
Some files converted to non-compatible format

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.go#29]
In certain cases, not sure if this is related to resolution or video quality, the yt downloader uses a VP80 Codec (https://www.screencast.com/t/YpjByam5) and not the typical web optimized h264. I remember we ran into something similar a while ago with John Cleese videos.

Here's an example: lbry://the-metagame-batman-arkham-asylum-20

Not sure what we can do in this case, but maybe we can force h264 or convert via ffpmeg.

**Comment by tzarebczan** [comment]
Another recent one: lbry://what-is-an-etf#3ab1078328232fe17700815ae35e582ee8c185cd

**Comment by tzarebczan** [comment]
Another: lbry://left-boy-get-it-right-sped-up#110aad98da20d92fc9f07e99dc7229cb4f979272

**Comment by tzarebczan** [comment]
@nikooo777 and I looked into this, and he has a way of removing VP8 codecs as an output method. Please close once it's been implemented.

**Comment by nikooo777** [comment]
I implemented this in a slightly different way than we discussed yesterday but it works the same.

Closing this as it's live!

**Comment by tzarebczan** [comment]
Reopening this as I think it caused issues on ALL videos synced since it was implemented. @nikooo777 can you confirm? How do we remedy this? 

I checked out a random new channel that was synced: lbry://@Prophetz and it's running into the metadata issue - VP8 codec with a low resolution.

**Comment by nikooo777** [comment]
@ all-hands: Tom and I figured out what happened and we're working on a fix.

we fixed the codec issue and now we're dealing with the wrongly synced content.
