### ISSUE TITLE
for ytsync, detect when lbrycrd is not running and error appropriately

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry.go#3]
### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by alyssaoc** [comment]
Issue moved to [lbryio/ytsync #10](https://github.com/lbryio/ytsync/issues/10) via [**ZenHub**](https://www.zenhub.com/)
