### ISSUE TITLE
Delay syncing video if newly posted / not post processed

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.go#42]
I think we may sometimes run into a scenario where we sync a video before it is post-processed in 720P+ on YouTube so we end up syncing a lower quality version. We should check when the video was posted, and if it's very recent (not sure what the timing for post-processing looks like), delay download/publish until the next iteration.

**Comment by alyssaoc** [comment]
Issue moved to [lbryio/ytsync #3](https://github.com/lbryio/ytsync/issues/3) via [**ZenHub**](https://www.zenhub.com/)
