### ISSUE TITLE
Outdated SeedNodes in dht/conf

### ISSUE THREAD

**Issue by AlessandroSpallina** [lbryio/lbry.go#81]
dht configs are outdated:
see https://github.com/lbryio/lbry.go/blob/ef1b10b601db3211ce4cd4923b10003be606fe07/dht/config.go#L68

use this instead:
```
SeedNodes: []string{
			"lbrynet1.lbry.com:4444",
			"lbrynet2.lbry.com:4444",
			"lbrynet3.lbry.com:4444",
                        "lbrynet4.lbry.com:4444",
		}
```

**Comment by lyoshenka** [comment]
:+1: https://github.com/lbryio/lbry.go/commit/21017a38a7ccc8a786edc77d995c3f89d064e13f

**Comment by tzarebczan** [comment]
@AlessandroSpallina , can we show you some [appreciation](https://lbry.com/faq/appreciation) for the report?

**Comment by AlessandroSpallina** [comment]
@tzarebczan thank you for the proposal, but there is not need, you have already shown your appreciation in the past :)
