### ISSUE TITLE
rename youtube video files

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.go#9]
Rather than publishing the file as the unique id inserted into YouTube, can we instead have a smarter algorithm that trims/compresses the video title?

Something like following replaces coupled with a 25-30 char limit would probably get most of the way:

`/[^\p{L}]//`
`/\s+/-`

A smarter version could split on spaces/dashes and try to ensure it only uses a whole number of words.

**Comment by nikooo777** [comment]
I suggest we use the same naming convention we have for claim names: https://github.com/lbryio/lbry.go/blob/master/ytsync/sources/youtubeVideo.go#L61

we could improve this function too and thus limit high fees based on long claim names

**Comment by nikooo777** [comment]
feature added and working fine :)
